/**
 * Append-only schema barrel.
 *
 * One file per feature (see plans/hackathon-starter/04-database-and-migrations.md).
 * Adding a table = new file + one export line at the bottom. Two people adding tables
 * on the same day touch two different lines, so this file does not merge-conflict.
 */

// `./auth` is GENERATED by `npm run auth:generate` (the Better Auth CLI reads
// `additionalFields` from `src/lib/auth.ts`). Never hand-edit it — re-run the CLI.
// Tables: user, session, account, verification.
export * from './auth'

export * from './courses'
export * from './learning'
export * from './engagement'
export * from './social'
